title: Página de Iván VM
author: ivancloudvm
email: ivancloudvm@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Usaré esta página para mostrar contenido que voy creando. 

# social links
twitter_username: N/A # DO NOT include the @ character, or else the build will fail!
github_username:  ivancloudvm # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
